### PR TITLE
Extra flag -i to invert black and white (negative photo).

### PR DESCRIPTION
**Pull request by Deleplace**
png negative

text-art negative

### CODE REVIEW

**Comment by Deleplace** [comment]
This may be useful mostly in combination with `-t`, when using a terminal that has white background and black text.

**Comment by Deleplace** [comment]
Ouch, suggested flag `-i` clashes with PR #5. Sorry about that

**Comment by hoangtuananhk56** [comment]
Hi,
Please help me answer why i type the command line is qrcode -t -i abc on terminal. It shows result qrcode but i want to get image abc.png. where is it? And how to take it?
Thanks
Anh

**Comment by skip2** [comment]
Try this:

`qrcode hello > abc.png`

**Comment by hoangtuananhk56** [comment]
well, many thanks. I got it ^^

**Pull request merged**
